x-env: &env
  environment:
    DB_HOST: db
    DB_USER: root
    DB_PASS: password
    MYSQL_ROOT_PASSWORD: password
    TZ: "Asia/Tokyo"

x-settings: &settings
  init: true

services:
  db:
    <<: [*env, *settings]
    image: mysql:8.0
    command:
      - '--bind-address=0.0.0.0'
      - '--character-set-server=utf8mb4'
    volumes:
      - type: volume
        source: mysqldata
        target: /var/lib/mysql
    ports:
      - '3306:3306'
  web:
    <<: [*env, *settings]
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: gemdata
        target: /usr/local/bundle
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bin/dev"
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  gemdata:
  mysqldata:
